version: '3.8'

services:
  # 🌐 Eureka Server
  ms-registry-server:
    build: ./registry-server
    container_name: ms-registry-server
    ports:
      - "8761:8761" # http://localhost:8761

  # ⚙️ Config Server
  ms-config-server:
    build: ./config-server
    container_name: ms-config-server
    depends_on:
      - ms-registry-server
    environment:
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
    ports:
      - "8888:8888" # http://localhost:8888

  # 🧑‍💼 Admin Core Service
  ms-admin-core:
    build: ./admin-core-service
    container_name: ms-admin-core
    depends_on:
      - ms-config-server
      - ms-registry-server
    environment:
      CONFIG_SERVER_HOST: https://config-server-production-c082.up.railway.app
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sRepFYJlbiIQvmduAOxmIkohYmpDtzNR
    ports:
      - "8081:8081" # http://localhost:8081/admin-service

  # 📊 Report Microservice
  ms-report:
    build: ./report-ms
    container_name: ms-report
    depends_on:
      - ms-config-server
      - ms-registry-server
    environment:
      CONFIG_SERVER_HOST: https://config-server-production-c082.up.railway.app
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
    ports:
      - "8082:8082" # http://localhost:8082/report-ms

  # 📈 Gráfico Report Microservice
  ms-report-grafico:
    build: ./report-grafico
    container_name: ms-report-grafico
    depends_on:
      - ms-config-server
      - ms-registry-server
    environment:
      CONFIG_SERVER_HOST: https://config-server-production-c082.up.railway.app
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
    ports:
      - "8083:8083" # http://localhost:8083/report-grafico

  # 🔐 Auth Service
  ms-auth-service:
    build: ./auth-service
    container_name: ms-auth-service
    depends_on:
      - ms-config-server
      - ms-registry-server
    environment:
      CONFIG_SERVER_HOST: https://config-server-production-c082.up.railway.app
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sRepFYJlbiIQvmduAOxmIkohYmpDtzNR
    ports:
      - "3030:3030" # http://localhost:3030/auth-service

  # ✉️ Notificaciones
  ms-notificacion-service:
    build: ./notificacion-service
    container_name: notificacion-service
    depends_on:
      - ms-registry-server
    environment:
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
    ports:
      - "5555:5555"

  # 🚪 API Gateway
  ms-gateway:
    build: ./gateway
    container_name: ms-gateway
    depends_on:
      - ms-registry-server
    environment:
      EUREKA_URL: https://registry-server-production-9b34.up.railway.app/eureka/
      SPRING_PROFILES_ACTIVE: oauth2
    ports:
      - "4040:4040" # http://localhost:4040

  # 🎨 Angular Frontend (serving over Nginx)
  ms-frontend:
    build: ./frontend/crediahorro
    container_name: ms-frontend
    depends_on:
      - ms-gateway
    ports:
      - "4200:80" # http://localhost:4200