spring:
  application:
    name: report-grafico
  config:
    #import: "configserver:http://localhost:8888"
    import: configserver:${CONFIG_SERVER_HOST}

server:
  port: 8083
  servlet:
    context-path: /report-grafico

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL}
